[package]
name = "raft"
version = "0.1.0"
edition = "2021"

[dependencies]
dsbuild = { path = "../../" }
serde = { version = "1.0.216", features = ["derive"]}
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["sync"]}
