[package]
name = "dsbuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
dslab-mp = { git = "https://github.com/osukhoroslov/dslab", version = "0.1.0" }
dyn-clone = "1.0.16"
serde = "1.0.193"
serde_json = "1.0.108"
sugars = "3.0.1"
timer = "0.2.0"
