[package]
name = "dsbuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
dslab-mp = { git = "https://github.com/osukhoroslov/dslab", version = "0.1.0" }
timer = "0.2.0"
