[package]
name = "dsbuild_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.38"
syn = "2.0.96"
dsbuild_message = { path = "../dsbuild-message" }
serde = "1.0.193"
serde_json = "1.0.108"

[lib]
proc-macro = true
