//! Definition of trait Context.

use super::message::Message;

/// Represents proxy, which provides process-system interaction.
pub trait Context {
    /// Sets a timer without overriding delay of existing one.
    fn set_timer_once(&mut self, name: String, delay: f64);

    /// Sets a timer with overriding delay of existing one.
    fn set_timer(&mut self, name: String, delay: f64);

    /// Cancel timer with certain name.
    /// If there is no such timer, does nothing.
    fn cancel_timer(&mut self, name: String);

    /// Send message to another process
    fn send_message(&mut self, msg: Message, to: String);

    /// Stop the process.
    /// If immediately flag is on, then all pending and further actions will be ignored.
    /// Else, process will be stopped only after handling all pending events and generated by them.
    /// In particular, new incomming network packages will be ignored.
    fn stop_process(&mut self, immediately: bool);
}
